name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Set up Snyk CLI to check for security issues
        run: snyk auth ${{ secrets.SNYK_API_TOKEN }}

      - name: Run Snyk test
        run: snyk test

      - name: Check for high-severity vulnerabilities
        run: |
          if snyk test --severity-threshold=high; then
            echo "No high-severity vulnerabilities found."
          else
            echo "High-severity vulnerabilities found. Failing the workflow."
            exit 1
          fi
