name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Authentication step
      - name: Authenticate with Snyk
        run: snyk auth ${{SNYK_API_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{SNYK_API_TOKEN }}
        with:
          args: --severity-threshold=high
