name: OpenSSF Scorecards 

on:
  pull_request:
    branches:
      - main

jobs:
  run-scorecard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Scorecard
      uses: ossf/scorecard-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo: ${{ github.repository }}
